Repository SE2-SS21-Gruppe4/Tick-Tack-Bumm, pull requests merged in 2021-05, with the labels that each got.

#13 First animations
  README.md
Labels: documentation

#33 Loading screenand player
  android/AndroidManifest.xml
  android/assets/loadingscreen.jpg
  android/assets/score/player1.png
  android/assets/score/player2.png
  android/assets/score/player3.png
  android/assets/score/player4.png
  android/assets/table.png
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/models/Score.java
  core/src/main/java/se2/ticktackbumm/core/models/attributes/Position.java
  core/src/main/java/se2/ticktackbumm/core/screens/LoadingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
Labels: feature

#36 Feature/text field
  core/src/main/java/se2/ticktackbumm/core/gamelogic/TextfieldInputListener.java
  core/src/test/java/se2/ticktackbumm/core/gamelogic/TextfieldInputListenerTest.java
Labels: enhancement, feature

#34 Feature/game data
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClient.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/data/GameMode.java
  core/src/main/java/se2/ticktackbumm/core/gamedata/GameData.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/ConnectionRejected.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/ConnectionSuccessful.java
  core/src/main/java/se2/ticktackbumm/core/player/Player.java
  core/src/main/java/se2/ticktackbumm/core/screens/LoadingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MenuScreen.java
  server/src/main/java/se2/ticktackbumm/server/Main.java
  server/src/main/java/se2/ticktackbumm/server/data/GameState.java
  server/src/main/java/se2/ticktackbumm/server/data/ServerData.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServer.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/test/java/ConnectionTests.java
Labels: architect, feature

#32 Spin wheel
  android/assets/ui/uiskin.json
  core/src/main/java/se2/ticktackbumm/core/models/WordPosition.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
Labels: feature

#31 Feature/card implementations
  android/assets/card/backside.jpg
  android/assets/card/frontside.png
  core/src/main/java/se2/ticktackbumm/core/models/Card.java
  core/src/main/java/se2/ticktackbumm/core/models/Cards/Card.java
  core/src/main/java/se2/ticktackbumm/core/models/Cards/CardWords.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
Labels: feature

#42 First prototype
  android/assets/card/backside.jpg
  android/assets/card/backside.png
  android/assets/card/frontside.png
  android/assets/maxScoreBoard.png
  android/assets/table.jpg
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/gamelogic/TextfieldInputListener.java
  core/src/main/java/se2/ticktackbumm/core/models/Cards/Card.java
  core/src/main/java/se2/ticktackbumm/core/models/Cards/CardWords.java
  core/src/main/java/se2/ticktackbumm/core/models/WordPosition.java
  core/src/main/java/se2/ticktackbumm/core/models/cards/Card.java
  core/src/main/java/se2/ticktackbumm/core/screens/LaunchScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/LoadingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MenuScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/RulesScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WaitingScreen.java
  core/src/test/java/se2/ticktackbumm/core/gamelogic/TextfieldInputListenerTest.java
Labels: enhancement, feature, user-interface

#43 First prototype
  README.md
  android/assets/menuscreen.png
  android/assets/rulescreen.png
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClient.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/gamelogic/TextfieldInputListener.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/BombExploded.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/ConnectionSuccessful.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/PlayerTaskCompleted.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/SomeRequest.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/SomeResponse.java
  core/src/main/java/se2/ticktackbumm/core/player/Player.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MenuScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/RulesScreen.java
  server/src/main/java/se2/ticktackbumm/server/data/ServerData.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServer.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
  server/src/test/java/ConnectionTests.java
Labels: enhancement

#54 Simple testing gameloop with 2 players and server
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/server/NextRound.java
  core/src/main/java/se2/ticktackbumm/core/player/Player.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
Labels: feature

#59 Loading screenetc
  android/assets/avatars/blackhaired_guy.png
  android/assets/avatars/blackhaired_guy_picked.png
  android/assets/avatars/blond_girl.png
  android/assets/avatars/blond_girl_picked.png
  android/assets/avatars/blond_guy.png
  android/assets/avatars/blond_guy_picked.png
  android/assets/avatars/brunette_girl.png
  android/assets/avatars/brunette_girl_picked.png
  android/assets/avatars/square_blue.png
  android/assets/avatars/square_green.png
  android/assets/avatars/square_red.png
  android/assets/avatars/square_yellow.png
  core/src/main/java/se2/ticktackbumm/core/data/Avatars.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/models/Score.java
  core/src/main/java/se2/ticktackbumm/core/network/NetworkConstants.java
  core/src/main/java/se2/ticktackbumm/core/player/Player.java
  core/src/main/java/se2/ticktackbumm/core/screens/LoadingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WaitingScreen.java
Labels: enhancement, feature

#60 Gamelogic/turnbased multiplayer architecture
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/server/GameFinished.java
  core/src/main/java/se2/ticktackbumm/core/player/Player.java
  core/src/main/java/se2/ticktackbumm/core/player/ScoreComparator.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  server/src/main/java/se2/ticktackbumm/server/data/ServerData.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
Labels: enhancement, feature
