Repository SE2-SS21-Gruppe4/Tick-Tack-Bumm, pull requests merged in 2021-06, with the labels that each got.

#66 Feature/bomb network
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/models/BombImpl/Bomb.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/BombStart.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
Labels: feature

#71 Spin wheel anim
  android/assets/ui/spin_wheel_ui.atlas
  android/assets/ui/spin_wheel_ui.png
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
Labels: feature, user-interface

#72 Fix game screen
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
Labels: bug

#73 Spin wheel animation networking
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/SpinWheelFinished.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
Labels: feature

#76 Spin wheel changes
  android/assets/ui/spin_wheel_ui.atlas
  android/assets/ui/spin_wheel_ui.png
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
Labels: user-interface

#84 Spin Wheel Changes #70 refactoring of some variables and methods
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  desktop/src/se2/ticktackbumm/desktop/DesktopLauncher.java
Labels: user-interface

#83 Add used words list with synchronization and resets
  .travis.yml
  android/assets/explosion.atlas
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/listeners/CheckButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/PlayerTaskCompleted.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/server/GameUpdate.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
Labels: enhancement

#89 Testing
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  core/src/test/java/se2/ticktackbumm/core/player/ScoreComparatorTest.java
  core/src/test/java/se2/ticktackbumm/core/screens/SpinWheelScreenTest.java
Labels: tests

#86 Spiel modus on main screen
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/SpinWheelStarted.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
Labels: feature, user-interface

#91 Continue code documentation and start code cleanup
  .travis.yml
  README.md
  android/assets/ui/uiskin.json
  android/project.properties
  android/res/drawable-anydpi-v26/ic_launcher_foreground.xml
  android/res/values/styles.xml
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/assets/Explosion.java
  core/src/main/java/se2/ticktackbumm/core/assets/Flame.java
  core/src/main/java/se2/ticktackbumm/core/assets/Lamp.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClient.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/listeners/AvatarButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/listeners/CheckButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/listeners/ReadyButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/models/BombImpl/Bomb.java
  core/src/main/java/se2/ticktackbumm/core/models/BombImpl/BombExplosion.java
  core/src/main/java/se2/ticktackbumm/core/models/Score.java
  core/src/main/java/se2/ticktackbumm/core/network/ClientHandler.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/NetworkConstants.java
  core/src/main/java/se2/ticktackbumm/core/network/Register.java
  core/src/main/java/se2/ticktackbumm/core/network/ServerHandler.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/SpinWheelFinished.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/StartBomb.java
  core/src/main/java/se2/ticktackbumm/core/player/Player.java
  core/src/main/java/se2/ticktackbumm/core/player/ScoreComparator.java
  core/src/main/java/se2/ticktackbumm/core/screens/LoadingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MenuScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/RulesScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/TestScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WaitingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WinnerScreen.java
  core/src/test/java/se2/ticktackbumm/core/player/ScoreComparatorTest.java
  core/src/test/java/se2/ticktackbumm/core/screens/SpinWheelScreenTest.java
  desktop/build.gradle
  desktop/src/se2/ticktackbumm/desktop/DesktopLauncher.java
  server/src/main/java/se2/ticktackbumm/server/data/ServerData.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServer.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
  server/src/test/java/ConnectionTests.java
Labels: documentation, enhancement

#95 Enhancement/documentation&cleanup
  .run/DesktopLauncher.run.xml
  core/src/main/java/se2/ticktackbumm/core/listeners/ReadyButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/models/MaxScore.java
  core/src/main/java/se2/ticktackbumm/core/models/RotatingWheel.java
  core/src/main/java/se2/ticktackbumm/core/models/TextInput.java
  core/src/main/java/se2/ticktackbumm/core/models/WordPosition.java
  core/src/main/java/se2/ticktackbumm/core/models/bomb/Bomb.java
  core/src/main/java/se2/ticktackbumm/core/models/bomb/BombExplosion.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/TestScreen.java
Labels: documentation

#96 Feature/winner
  android/assets/loadingscreen.jpg
  android/assets/menuScreen/background.png
  android/assets/rulescreen.png
  android/assets/waitingScreen/avatar.png
  android/assets/waitingScreen/avatarandname.png
  android/assets/waitingScreen/background.png
  android/assets/waitingScreen/name.png
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/listeners/ReadyButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/models/Score.java
  core/src/main/java/se2/ticktackbumm/core/player/Player.java
  core/src/main/java/se2/ticktackbumm/core/screens/LoadingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MenuScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/RulesScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WaitingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WinnerScreen.java
  desktop/src/se2/ticktackbumm/desktop/DesktopLauncher.java
  server/src/main/java/se2/ticktackbumm/server/data/ServerData.java
Labels: enhancement, feature

#90 Cards /network test
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/models/cards/Card.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/CardOpened.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/server/GameUpdate.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/test/java/se2/ticktackbumm/core/models/cards/CardTest.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
Labels: tests

#98 More documentation, tests and some cleanup of unused files.
  .run/DesktopLauncher.run.xml
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/listeners/CheckButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/listeners/ReadyButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/models/cards/Card.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/CardOpened.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/SpinWheelStarted.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/server/GameUpdate.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MenuScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/RulesScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WaitingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WinnerScreen.java
  core/src/test/java/se2/ticktackbumm/core/models/cards/CardTest.java
  server/src/main/java/se2/ticktackbumm/server/data/GameState.java
  server/src/main/java/se2/ticktackbumm/server/data/ServerData.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServer.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
  server/src/test/java/se2/ticktackbumm/server/data/ServerDataTest.java
Labels: documentation, tests

#101 Tests
  core/src/main/java/se2/ticktackbumm/core/listeners/ReadyButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/models/Score.java
  core/src/main/java/se2/ticktackbumm/core/models/cards/Card.java
  core/src/main/java/se2/ticktackbumm/core/network/NetworkConstants.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  core/src/test/java/se2/ticktackbumm/core/listeners/ReadyButtonListenerTest.java
  core/src/test/java/se2/ticktackbumm/core/models/ScoreTest.java
  core/src/test/java/se2/ticktackbumm/core/player/PlayerTest.java
Labels: enhancement, tests

#99 Bomb/network communication
  android/assets/bomb/bombexplosion1.mp3
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/models/bomb/Bomb.java
  core/src/main/java/se2/ticktackbumm/core/models/bomb/BombExplosion.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/StartBomb.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/server/GameUpdate.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/TestScreen.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
Labels: tests

#102 Banner game mode changes
  android/assets/bannerBackground.png
  android/assets/spinWheelScreen/background.png
  core/src/main/java/se2/ticktackbumm/core/screens/LoadingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
Labels: enhancement, user-interface

#104 Fix wheel, banners, card, bomb and improve design
  android/assets/card/backside.png
  android/assets/card/frontside.png
  android/assets/mainGameScreen/background.png
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/assets/Explosion.java
  core/src/main/java/se2/ticktackbumm/core/assets/Flame.java
  core/src/main/java/se2/ticktackbumm/core/assets/Lamp.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/data/Avatars.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/listeners/CheckButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/models/Card.java
  core/src/main/java/se2/ticktackbumm/core/models/Score.java
  core/src/main/java/se2/ticktackbumm/core/models/bomb/Bomb.java
  core/src/main/java/se2/ticktackbumm/core/models/bomb/BombExplosion.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/StartBomb.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/server/GameUpdate.java
  core/src/main/java/se2/ticktackbumm/core/screens/LoadingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/RulesScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WinnerScreen.java
  core/src/test/java/se2/ticktackbumm/core/listeners/ReadyButtonListenerTest.java
  core/src/test/java/se2/ticktackbumm/core/models/cards/CardTest.java
  core/src/test/java/se2/ticktackbumm/core/player/PlayerTest.java
  desktop/src/se2/ticktackbumm/desktop/DesktopLauncher.java
  server/src/main/java/se2/ticktackbumm/server/data/ServerData.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageSender.java
Labels: enhancement

#105 Spin wheel sound
  android/assets/spinWheelScreen/music-off-black.png
  android/assets/spinWheelScreen/music-off.png
  android/assets/spinWheelScreen/music-on-black.png
  android/assets/spinWheelScreen/music-on.png
  android/assets/spinWheelScreen/spinSound-1sec.mp3
  android/assets/spinWheelScreen/spinSound-2sec.mp3
  android/assets/spinWheelScreen/spinSound-3sec.mp3
  android/assets/spinWheelScreen/spinSound-4sec.mp3
  android/assets/spinWheelScreen/spinSound-5sec.mp3
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
Labels: enhancement

#106 Add cheat function and info label, fix bugs
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/assets/Explosion.java
  core/src/main/java/se2/ticktackbumm/core/assets/Flame.java
  core/src/main/java/se2/ticktackbumm/core/assets/Lamp.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageHandler.java
  core/src/main/java/se2/ticktackbumm/core/client/ClientMessageSender.java
  core/src/main/java/se2/ticktackbumm/core/client/NetworkClientListener.java
  core/src/main/java/se2/ticktackbumm/core/data/GameData.java
  core/src/main/java/se2/ticktackbumm/core/listeners/CheckButtonListener.java
  core/src/main/java/se2/ticktackbumm/core/models/Score.java
  core/src/main/java/se2/ticktackbumm/core/network/KryoRegisterer.java
  core/src/main/java/se2/ticktackbumm/core/network/messages/client/PlayerCheated.java
  core/src/main/java/se2/ticktackbumm/core/player/Player.java
  core/src/main/java/se2/ticktackbumm/core/screens/LoadingScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/RulesScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/WinnerScreen.java
  server/src/main/java/se2/ticktackbumm/server/data/ServerData.java
  server/src/main/java/se2/ticktackbumm/server/network/NetworkServerListener.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
  server/src/test/java/se2/ticktackbumm/server/data/ServerDataTest.java
Labels: bug, feature

#107 Dokumentation schreiben #100 write documentation
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
Labels: documentation

#108 Presentation
  core/src/main/java/se2/ticktackbumm/core/models/Card.java
  core/src/main/java/se2/ticktackbumm/core/models/bomb/Bomb.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
  core/src/main/java/se2/ticktackbumm/core/screens/SpinWheelScreen.java
  server/src/main/java/se2/ticktackbumm/server/network/ServerMessageHandler.java
Labels: enhancement

#109 Fix minor bugs
  core/src/main/java/se2/ticktackbumm/core/TickTackBummGame.java
  core/src/main/java/se2/ticktackbumm/core/screens/MainGameScreen.java
Labels: bug
